services:
  - type: web
    name: cash2switch-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c backend/gunicorn.conf.py backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0